export const CART = {
  ADD: 'CART_ADD',
  REMOVE: 'CART_REMOVE',
  COMPLETE: 'CART_COMPLETE',
  INCREASE: 'CART_INCREASE',
  DECREASE: 'CART_DECREASE',
  CHANGE_QUANTITY: 'CART_CHANGE_QUANTITY',
  CHECKOUT: 'CART_CHECKOUT',
  CLEAR: 'CART_CLEAR'
};